Enable pip check
conda-forge/pytorch-lightning-feedstock pull request #115
Opened 2023-01-25 23:52 UTC by jan-janssen

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-01-25 23:52 UTC, jan-janssen commented
@conda-forge-admin, please rerender

2023-01-25 23:55 UTC, jan-janssen commented
Fixes https://github.com/conda-forge/pytorch-lightning-feedstock/issues/114

2023-01-26 00:05 UTC, jan-janssen commented
@conda-forge-admin, please rerender

2023-01-26 11:48 UTC, Borda requested changes
I would split adding maintainer from fixing an issue, pls

2023-01-26 11:48 UTC, Borda commented on .github/CODEOWNERS
> +* @borda @carmocca @jan-janssen @williamFalcon
```suggestion
* @borda @carmocca @williamFalcon
```

2023-01-26 13:11 UTC, jan-janssen commented
@conda-forge-admin, please rerender

2023-01-26 13:14 UTC, jan-janssen commented
> I would split adding maintainer from fixing an issue, pls

Sure - no pressure. I just wanted to help out.

2023-01-28 02:30 UTC, Borda approved these changes

2023-01-28 02:32 UTC, merged