lightning 1.8.6
conda-forge/pytorch-lightning-feedstock pull request #140
Opened 2023-08-17 18:54 UTC by DManowitz

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Copied dependencies from pytorch-lightning 1.8.6 commit.

2023-08-17 18:56 UTC, DManowitz commented
@conda-forge-admin please rerender

2023-08-22 16:34 UTC, DManowitz commented
Hey, @Borda, @carmocca , @jan-janssen , or @williamFalcon, can one of you please review this PR?  I didn't see any past PRs that would create the `lightning` package as opposed to the `pytorch-lightning` package, so I based my changes off of the past PRs that I did see.  I may have been wrong in my approach, though because of that.

2023-08-22 18:43 UTC, Borda commented on recipe/meta.yaml
> +  summary: Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
```suggestion
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
```

2023-08-22 18:44 UTC, Borda requested changes
seem your changes shall be towards this package https://github.com/conda-forge/lightning-feedstock

2023-08-22 18:44 UTC, closed without merging